DELETE FROM achievement_criteria_data WHERE criteria_id=189;
DELETE FROM achievement_criteria_data WHERE criteria_id=190;
DELETE FROM achievement_criteria_data WHERE criteria_id=191;
DELETE FROM achievement_criteria_data WHERE criteria_id=192;
DELETE FROM achievement_criteria_data WHERE criteria_id=195;
DELETE FROM achievement_criteria_data WHERE criteria_id=196;
DELETE FROM achievement_criteria_data WHERE criteria_id=197;
DELETE FROM achievement_criteria_data WHERE criteria_id=198;
DELETE FROM achievement_criteria_data WHERE criteria_id=199;
DELETE FROM achievement_criteria_data WHERE criteria_id=200;
DELETE FROM achievement_criteria_data WHERE criteria_id=201;
DELETE FROM achievement_criteria_data WHERE criteria_id=203;
DELETE FROM achievement_criteria_data WHERE criteria_id=204;
DELETE FROM achievement_criteria_data WHERE criteria_id=205;
DELETE FROM achievement_criteria_data WHERE criteria_id=206;
DELETE FROM achievement_criteria_data WHERE criteria_id=207;
DELETE FROM achievement_criteria_data WHERE criteria_id=208;
DELETE FROM achievement_criteria_data WHERE criteria_id=209;
DELETE FROM achievement_criteria_data WHERE criteria_id=210;
DELETE FROM achievement_criteria_data WHERE criteria_id=211;
DELETE FROM achievement_criteria_data WHERE criteria_id=212;
DELETE FROM achievement_criteria_data WHERE criteria_id=213;
DELETE FROM achievement_criteria_data WHERE criteria_id=215;
DELETE FROM achievement_criteria_data WHERE criteria_id=216;
DELETE FROM achievement_criteria_data WHERE criteria_id=217;
DELETE FROM achievement_criteria_data WHERE criteria_id=218;
DELETE FROM achievement_criteria_data WHERE criteria_id=219;
DELETE FROM achievement_criteria_data WHERE criteria_id=220;
DELETE FROM achievement_criteria_data WHERE criteria_id=351;
DELETE FROM achievement_criteria_data WHERE criteria_id=352;
DELETE FROM achievement_criteria_data WHERE criteria_id=353;
DELETE FROM achievement_criteria_data WHERE criteria_id=357;
DELETE FROM achievement_criteria_data WHERE criteria_id=358;
DELETE FROM achievement_criteria_data WHERE criteria_id=359;
DELETE FROM achievement_criteria_data WHERE criteria_id=360;
DELETE FROM achievement_criteria_data WHERE criteria_id=365;
DELETE FROM achievement_criteria_data WHERE criteria_id=366;
DELETE FROM achievement_criteria_data WHERE criteria_id=367;
DELETE FROM achievement_criteria_data WHERE criteria_id=372;
DELETE FROM achievement_criteria_data WHERE criteria_id=373;
DELETE FROM achievement_criteria_data WHERE criteria_id=379;
DELETE FROM achievement_criteria_data WHERE criteria_id=381;
DELETE FROM achievement_criteria_data WHERE criteria_id=382;
DELETE FROM achievement_criteria_data WHERE criteria_id=520;
DELETE FROM achievement_criteria_data WHERE criteria_id=521;
DELETE FROM achievement_criteria_data WHERE criteria_id=523;
DELETE FROM achievement_criteria_data WHERE criteria_id=555;
DELETE FROM achievement_criteria_data WHERE criteria_id=556;
DELETE FROM achievement_criteria_data WHERE criteria_id=557;
DELETE FROM achievement_criteria_data WHERE criteria_id=558;
DELETE FROM achievement_criteria_data WHERE criteria_id=559;
DELETE FROM achievement_criteria_data WHERE criteria_id=560;
DELETE FROM achievement_criteria_data WHERE criteria_id=561;
DELETE FROM achievement_criteria_data WHERE criteria_id=562;
DELETE FROM achievement_criteria_data WHERE criteria_id=563;
DELETE FROM achievement_criteria_data WHERE criteria_id=564;
DELETE FROM achievement_criteria_data WHERE criteria_id=565;
DELETE FROM achievement_criteria_data WHERE criteria_id=566;
DELETE FROM achievement_criteria_data WHERE criteria_id=567;
DELETE FROM achievement_criteria_data WHERE criteria_id=568;
DELETE FROM achievement_criteria_data WHERE criteria_id=573;
DELETE FROM achievement_criteria_data WHERE criteria_id=1827;
DELETE FROM achievement_criteria_data WHERE criteria_id=2041;
DELETE FROM achievement_criteria_data WHERE criteria_id=2042;
DELETE FROM achievement_criteria_data WHERE criteria_id=2043;
DELETE FROM achievement_criteria_data WHERE criteria_id=4244;
DELETE FROM achievement_criteria_data WHERE criteria_id=7126;
DELETE FROM achievement_criteria_data WHERE criteria_id=7127;
DELETE FROM achievement_criteria_data WHERE criteria_id=7128;
DELETE FROM achievement_criteria_data WHERE criteria_id=7129;
DELETE FROM achievement_criteria_data WHERE criteria_id=7130;
DELETE FROM achievement_criteria_data WHERE criteria_id=7133;
DELETE FROM achievement_criteria_data WHERE criteria_id=7143;
DELETE FROM achievement_criteria_data WHERE criteria_id=7144;
DELETE FROM achievement_criteria_data WHERE criteria_id=7145;
DELETE FROM achievement_criteria_data WHERE criteria_id=7180;
DELETE FROM achievement_criteria_data WHERE criteria_id=7181;
DELETE FROM achievement_criteria_data WHERE criteria_id=7595;
DELETE FROM achievement_criteria_data WHERE criteria_id=10080;
DELETE FROM achievement_criteria_data WHERE criteria_id=10081;
DELETE FROM achievement_criteria_data WHERE criteria_id=10082;
DELETE FROM achievement_criteria_data WHERE criteria_id=10083;
DELETE FROM achievement_criteria_data WHERE criteria_id=10084;
DELETE FROM achievement_criteria_data WHERE criteria_id=10085;
DELETE FROM achievement_criteria_data WHERE criteria_id=10086;
DELETE FROM achievement_criteria_data WHERE criteria_id=10087;
DELETE FROM achievement_criteria_data WHERE criteria_id=10090;
DELETE FROM achievement_criteria_data WHERE criteria_id=10091;
DELETE FROM achievement_criteria_data WHERE criteria_id=10095;
DELETE FROM achievement_criteria_data WHERE criteria_id=10099;
DELETE FROM achievement_criteria_data WHERE criteria_id=10133;
DELETE FROM achievement_criteria_data WHERE criteria_id=10185;
DELETE FROM achievement_criteria_data WHERE criteria_id=10279;
DELETE FROM achievement_criteria_data WHERE criteria_id=10284;
DELETE FROM achievement_criteria_data WHERE criteria_id=10285;
DELETE FROM achievement_criteria_data WHERE criteria_id=10286;
DELETE FROM achievement_criteria_data WHERE criteria_id=10290;
DELETE FROM achievement_criteria_data WHERE criteria_id=10291;
DELETE FROM achievement_criteria_data WHERE criteria_id=10292;
DELETE FROM achievement_criteria_data WHERE criteria_id=10293;
DELETE FROM achievement_criteria_data WHERE criteria_id=10294;
DELETE FROM achievement_criteria_data WHERE criteria_id=10296;
DELETE FROM achievement_criteria_data WHERE criteria_id=10388;
DELETE FROM achievement_criteria_data WHERE criteria_id=10409;
DELETE FROM achievement_criteria_data WHERE criteria_id=10410;
DELETE FROM achievement_criteria_data WHERE criteria_id=10412;
DELETE FROM achievement_criteria_data WHERE criteria_id=10414;
DELETE FROM achievement_criteria_data WHERE criteria_id=10415;
DELETE FROM achievement_criteria_data WHERE criteria_id=10416;
DELETE FROM achievement_criteria_data WHERE criteria_id=10417;
DELETE FROM achievement_criteria_data WHERE criteria_id=10422;
DELETE FROM achievement_criteria_data WHERE criteria_id=10423;
DELETE FROM achievement_criteria_data WHERE criteria_id=10424;
DELETE FROM achievement_criteria_data WHERE criteria_id=10425;
DELETE FROM achievement_criteria_data WHERE criteria_id=10450;
DELETE FROM achievement_criteria_data WHERE criteria_id=10463;
DELETE FROM achievement_criteria_data WHERE criteria_id=10544;
DELETE FROM achievement_criteria_data WHERE criteria_id=10545;
DELETE FROM achievement_criteria_data WHERE criteria_id=10546;
DELETE FROM achievement_criteria_data WHERE criteria_id=10547;
DELETE FROM achievement_criteria_data WHERE criteria_id=10548;
DELETE FROM achievement_criteria_data WHERE criteria_id=10722;
DELETE FROM achievement_criteria_data WHERE criteria_id=11778;
DELETE FROM achievement_criteria_data WHERE criteria_id=12752;
DELETE FROM achievement_criteria_data WHERE criteria_id=13000;
DELETE FROM achievement_criteria_data WHERE criteria_id=17986;
DELETE FROM achievement_criteria_data WHERE criteria_id=17987;
DELETE FROM achievement_criteria_data WHERE criteria_id=17988;
DELETE FROM achievement_criteria_data WHERE criteria_id=17989;
DELETE FROM achievement_criteria_data WHERE criteria_id=17990;
DELETE FROM achievement_criteria_data WHERE criteria_id=17991;
DELETE FROM achievement_criteria_data WHERE criteria_id=17992;
DELETE FROM achievement_criteria_data WHERE criteria_id=17993;
DELETE FROM achievement_criteria_data WHERE criteria_id=17994;
DELETE FROM achievement_criteria_data WHERE criteria_id=17995;
DELETE FROM achievement_criteria_data WHERE criteria_id=17996;
DELETE FROM achievement_criteria_data WHERE criteria_id=17997;
DELETE FROM achievement_criteria_data WHERE criteria_id=18048;
DELETE FROM achievement_criteria_data WHERE criteria_id=18049;
DELETE FROM achievement_criteria_data WHERE criteria_id=18050;
DELETE FROM achievement_criteria_data WHERE criteria_id=18051;
DELETE FROM achievement_criteria_data WHERE criteria_id=18052;
DELETE FROM achievement_criteria_data WHERE criteria_id=18053;
DELETE FROM achievement_criteria_data WHERE criteria_id=18054;
DELETE FROM achievement_criteria_data WHERE criteria_id=18055;
DELETE FROM achievement_criteria_data WHERE criteria_id=18056;
DELETE FROM achievement_criteria_data WHERE criteria_id=18057;
DELETE FROM achievement_criteria_data WHERE criteria_id=18058;
DELETE FROM achievement_criteria_data WHERE criteria_id=18059;
DELETE FROM achievement_criteria_data WHERE criteria_id=18060;
DELETE FROM achievement_criteria_data WHERE criteria_id=18061;
DELETE FROM achievement_criteria_data WHERE criteria_id=18062;
DELETE FROM achievement_criteria_data WHERE criteria_id=18063;
DELETE FROM achievement_criteria_data WHERE criteria_id=18064;
DELETE FROM achievement_criteria_data WHERE criteria_id=18065;
DELETE FROM achievement_criteria_data WHERE criteria_id=18066;
DELETE FROM achievement_criteria_data WHERE criteria_id=18067;
DELETE FROM achievement_criteria_data WHERE criteria_id=18068;
DELETE FROM achievement_criteria_data WHERE criteria_id=18069;
DELETE FROM achievement_criteria_data WHERE criteria_id=18070;
DELETE FROM achievement_criteria_data WHERE criteria_id=18071;
DELETE FROM achievement_criteria_data WHERE criteria_id=18074;
DELETE FROM achievement_criteria_data WHERE criteria_id=18075;
DELETE FROM achievement_criteria_data WHERE criteria_id=18454;
DELETE FROM achievement_criteria_data WHERE criteria_id=18455;
DELETE FROM achievement_criteria_data WHERE criteria_id=18456;
DELETE FROM achievement_criteria_data WHERE criteria_id=18457;
DELETE FROM achievement_criteria_data WHERE criteria_id=18458;
DELETE FROM achievement_criteria_data WHERE criteria_id=18459;
DELETE FROM achievement_criteria_data WHERE criteria_id=18460;
DELETE FROM achievement_criteria_data WHERE criteria_id=18461;
DELETE FROM achievement_criteria_data WHERE criteria_id=18462;
DELETE FROM achievement_criteria_data WHERE criteria_id=18463;
DELETE FROM achievement_criteria_data WHERE criteria_id=18464;
DELETE FROM achievement_criteria_data WHERE criteria_id=18465;
DELETE FROM achievement_criteria_data WHERE criteria_id=18473;
DELETE FROM achievement_criteria_data WHERE criteria_id=18501;
DELETE FROM achievement_criteria_data WHERE criteria_id=18545;
DELETE FROM achievement_criteria_data WHERE criteria_id=18546;
DELETE FROM achievement_criteria_data WHERE criteria_id=18547;
DELETE FROM achievement_criteria_data WHERE criteria_id=18548;
DELETE FROM achievement_criteria_data WHERE criteria_id=18549;
DELETE FROM achievement_criteria_data WHERE criteria_id=18550;
DELETE FROM achievement_criteria_data WHERE criteria_id=18551;
DELETE FROM achievement_criteria_data WHERE criteria_id=18552;
DELETE FROM achievement_criteria_data WHERE criteria_id=18553;
DELETE FROM achievement_criteria_data WHERE criteria_id=18554;
DELETE FROM achievement_criteria_data WHERE criteria_id=18555;
DELETE FROM achievement_criteria_data WHERE criteria_id=18556;
DELETE FROM achievement_criteria_data WHERE criteria_id=18565;
DELETE FROM achievement_criteria_data WHERE criteria_id=18566;
DELETE FROM achievement_criteria_data WHERE criteria_id=18567;
DELETE FROM achievement_criteria_data WHERE criteria_id=18568;
DELETE FROM achievement_criteria_data WHERE criteria_id=18569;
DELETE FROM achievement_criteria_data WHERE criteria_id=18570;
DELETE FROM achievement_criteria_data WHERE criteria_id=18571;
DELETE FROM achievement_criteria_data WHERE criteria_id=18572;
DELETE FROM achievement_criteria_data WHERE criteria_id=18573;
DELETE FROM achievement_criteria_data WHERE criteria_id=18574;
DELETE FROM achievement_criteria_data WHERE criteria_id=18575;
DELETE FROM achievement_criteria_data WHERE criteria_id=18576;
DELETE FROM achievement_criteria_data WHERE criteria_id=18669;
DELETE FROM achievement_criteria_data WHERE criteria_id=18673;
DELETE FROM achievement_criteria_data WHERE criteria_id=18674;
DELETE FROM achievement_criteria_data WHERE criteria_id=18675;
DELETE FROM achievement_criteria_data WHERE criteria_id=18676;
DELETE FROM achievement_criteria_data WHERE criteria_id=18677;
DELETE FROM achievement_criteria_data WHERE criteria_id=18678;
DELETE FROM achievement_criteria_data WHERE criteria_id=18679;
DELETE FROM achievement_criteria_data WHERE criteria_id=18680;
DELETE FROM achievement_criteria_data WHERE criteria_id=18681;
DELETE FROM achievement_criteria_data WHERE criteria_id=18682;
DELETE FROM achievement_criteria_data WHERE criteria_id=18683;
DELETE FROM achievement_criteria_data WHERE criteria_id=18684;

INSERT INTO `achievement_criteria_data` VALUES (189, 0, 23593, 1, '');
INSERT INTO `achievement_criteria_data` VALUES (190, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (191, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (192, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (195, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (196, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (197, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (198, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (199, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (200, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (201, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (203, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (204, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (205, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (206, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (207, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (208, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (209, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (210, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (211, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (212, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (213, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (215, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (216, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (217, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (218, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (219, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (220, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (351, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (352, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (353, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (357, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (358, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (359, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (360, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (365, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (366, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (367, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (372, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (373, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (379, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (381, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (382, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (520, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (521, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (523, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (555, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (556, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (557, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (558, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (559, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (560, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (561, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (562, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (563, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (564, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (565, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (566, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (567, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (568, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (573, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (1827, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (2041, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (2042, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (2043, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (4244, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7126, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7127, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7128, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7129, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7130, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7133, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7143, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7144, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7145, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7180, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7181, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (7595, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10080, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10081, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10082, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10083, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10084, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10085, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10086, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10087, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10090, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10091, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10095, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10099, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10133, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10185, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10279, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10284, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10285, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10286, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10290, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10291, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10292, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10293, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10294, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10296, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10388, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10409, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10410, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10412, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10414, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10415, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10416, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10417, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10422, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10423, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10424, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10425, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10450, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10463, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10544, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10545, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10546, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10547, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10548, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (10722, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (11778, 0, 34497, 1, '');
INSERT INTO `achievement_criteria_data` VALUES (12752, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17986, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17987, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17988, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17989, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17990, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17991, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17992, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17993, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17994, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17995, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17996, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (17997, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18048, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18049, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18050, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18051, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18052, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18053, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18054, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18055, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18056, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18057, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18058, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18059, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18060, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18061, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18062, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18063, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18064, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18065, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18066, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18067, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18068, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18069, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18070, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18071, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18074, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18075, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18454, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18455, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18456, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18457, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18458, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18459, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18460, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18461, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18462, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18463, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18464, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18465, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18473, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18501, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18545, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18546, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18547, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18548, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18549, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18550, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18551, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18552, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18553, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18554, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18555, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18556, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18565, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18566, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18567, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18568, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18569, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18570, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18571, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18572, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18573, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18574, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18575, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18576, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18669, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18673, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18674, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18675, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18676, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18677, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18678, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18679, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18680, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18681, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18682, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18683, 0, 0, 0, '');
INSERT INTO `achievement_criteria_data` VALUES (18684, 0, 0, 0, '');
