DELETE FROM creature_template WHERE entry=71234;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (71234, 0, 0, 0, 0, 0, 11686, 0, 0, 0, '[DNT] Darkmoon Faire Tonk Commander Controller', '', NULL, 0, 60, 60, 0, 0, 35, 35, 0, 1, 1.14286, 1.14286, 1, 0, 2, 2, 0, 24, 1, 2000, 0, 1, 33554432, 2048, 8, 0, 0, 0, 0, 0, 1, 1, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 1.35, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 128, 'npc_darkmoon_faire_tonk_commander_controller', 0);
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_tonk_target' WHERE (`entry`='33081');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_tonk' WHERE (`entry`='54588');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_enemy_tonk' WHERE (`entry`='54642');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_teleporters' WHERE (`entry`='55382');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_target_controller' WHERE (`entry`='24220');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_target_bunny' WHERE (`entry`='24171');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_korgol_crushskull' WHERE (`entry`='55402');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_jubjub' WHERE (`entry`='14867');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_injured_carnie' WHERE (`entry`='54518');
UPDATE `creature_template` SET `ScriptName`='npc_darkmoon_faire_enemy_minizep' WHERE (`entry`='54643');
UPDATE `gameobject_template` SET `ScriptName`='go_darkmoon_faire_darkmoon_cannon_balls' WHERE (`entry`='209332');
UPDATE `gameobject_template` SET `ScriptName`='go_darkmoon_faire_darkmoon_treasure_chest' WHERE (`entry`='209620');
DELETE FROM spell_script_names WHERE spell_id IN (101695,101697,101612,101994,102022,100752,108941,113212,113213,113216,113219,113224,113227,113228,23853,62172,101838,101871,101872,101883,102113,102115,108919);
INSERT INTO `spell_script_names` VALUES ('101695', 'spell_darkmoon_faire_ring_toss');
INSERT INTO `spell_script_names` VALUES ('101697', 'spell_darkmoon_faire_ring_toss_missile');
INSERT INTO `spell_script_names` VALUES ('101612', 'spell_darkmoon_faire_whack_a_gnoll_aura');
INSERT INTO `spell_script_names` VALUES ('101994', 'spell_darkmoon_faire_whack_a_gnoll_summon_aura');
INSERT INTO `spell_script_names` VALUES ('102022', 'spell_darkmoon_faire_whack');
INSERT INTO `spell_script_names` VALUES ('100752', 'spell_darkmoon_faire_using_darkmoon_tonk_controller');
INSERT INTO `spell_script_names` VALUES ('108941', 'spell_darkmoon_faire_darkmoon_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113212', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113213', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113216', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113219', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113224', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113227', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('113228', 'spell_darkmoon_faire_enter_deathmatch');
INSERT INTO `spell_script_names` VALUES ('23853', 'spell_darkmoon_faire_jubling_cooldown');
INSERT INTO `spell_script_names` VALUES ('62172', 'spell_darkmoon_faire_just_shot_from_cannon');
INSERT INTO `spell_script_names` VALUES ('101838', 'spell_darkmoon_faire_target_conditions');
INSERT INTO `spell_script_names` VALUES ('101871', 'spell_darkmoon_faire_crack_shot');
INSERT INTO `spell_script_names` VALUES ('101872', 'spell_darkmoon_faire_shoot_rifle');
INSERT INTO `spell_script_names` VALUES ('101883', 'spell_darkmoon_faire_target_conditions');
INSERT INTO `spell_script_names` VALUES ('102113', 'spell_darkmoon_faire_cannon_prep');
INSERT INTO `spell_script_names` VALUES ('102115', 'spell_darkmoon_faire_fire_cannon');
INSERT INTO `spell_script_names` VALUES ('108919', 'spell_darkmoon_faire_enter_deathmatch');